[install]
git = {}
cmake = {}
pkg-config = {}
pcre = {}
libgcrypt = {}
libevent = {}
openssl = {}
icu58 = {}
gnumake = {}
coreutils = {}
inetutils = {}
jemalloc = {}
vim = {}
zlib = {}
bison = {}
mysql-client = {}

[vars]
ICQ_DIR="$FLOX_ENV"
ICU_ROOT="$FLOX_ENV"
OPENSSL_ROOT_DIR="$FLOX_ENV"
MYSQL_ROOT="$FLOX_ENV"
ZLIB_ROOT="$FLOX_ENV"
PCRE_ROOT="$FLOX_ENV"
JEMALLOC_ROOT="$FLOX_ENV"

