[install]
git = {}
cmake = {}
pkg-config = {}
pcre = {}
libgcrypt = {}
libevent = {}
openssl = {}
gcc = {}
icu = {}
mariadb-connector-c = {}
gnumake = {}
coreutils = {}
inetutils = {}
jemalloc = {}
vim = {}
zlib = {}
bison = {}

[vars]
ICU_ROOT="$FLOX_ENV"
OPENSSL_ROOT_DIR="$FLOX_ENV"
ZLIB_ROOT="$FLOX_ENV"
PCRE_ROOT="$FLOX_ENV"

